import type { Theme } from "../../types.js";

export const highContrastLightTheme: Theme = {
  border: {
    color: "#000000",
    focusColor: "#0000CC",
    style: "bold",
  },
  colors: {
    accent: "#004499",
    accentForeground: "#FFFFFF",
    background: "#FFFFFF",
    border: "#000000",
    error: "#CC0000",
    errorForeground: "#FFFFFF",
    focusRing: "#0000CC",
    foreground: "#000000",
    info: "#004499",
    infoForeground: "#FFFFFF",
    muted: "#F0F0F0",
    mutedForeground: "#444444",
    primary: "#000000",
    primaryForeground: "#FFFFFF",
    secondary: "#6600CC",
    secondaryForeground: "#FFFFFF",
    selection: "#000000",
    selectionForeground: "#FFFFFF",
    success: "#006600",
    successForeground: "#FFFFFF",
    warning: "#884400",
    warningForeground: "#FFFFFF",
  },
  name: "high-contrast-light",
  spacing: {
    0: 0,
    1: 1,
    2: 2,
    3: 3,
    4: 4,
    6: 6,
    8: 8,
  },
  typography: {
    base: "",
    bold: true,
    lg: "bold",
    sm: "dim",
    xl: "bold",
  },
};
