import type { Theme } from "../../types.js";

export const highContrastTheme: Theme = {
  border: {
    color: "#FFFFFF",
    focusColor: "#FFFF00",
    style: "bold",
  },
  colors: {
    accent: "#00FFFF",
    accentForeground: "#000000",
    background: "#000000",
    border: "#FFFFFF",
    error: "#FF4444",
    errorForeground: "#FFFFFF",
    focusRing: "#FFFF00",
    foreground: "#FFFFFF",
    info: "#00CCFF",
    infoForeground: "#000000",
    muted: "#1A1A1A",
    mutedForeground: "#CCCCCC",
    primary: "#FFFFFF",
    primaryForeground: "#000000",
    secondary: "#FFFF00",
    secondaryForeground: "#000000",
    selection: "#FFFFFF",
    selectionForeground: "#000000",
    success: "#00FF00",
    successForeground: "#000000",
    warning: "#FFFF00",
    warningForeground: "#000000",
  },
  name: "high-contrast",
  spacing: {
    0: 0,
    1: 1,
    2: 2,
    3: 3,
    4: 4,
    6: 6,
    8: 8,
  },
  typography: {
    base: "",
    bold: true,
    lg: "bold",
    sm: "dim",
    xl: "bold",
  },
};
