import type { Theme } from "../../types.js";

export const matrixTheme: Theme = {
  border: {
    color: "#8ca391",
    focusColor: "#c770ff",
    style: "round",
  },
  colors: {
    accent: "#c770ff",
    accentForeground: "#0a0e0a",
    background: "#0a0e0a",
    border: "#8ca391",
    error: "#ff4b4b",
    errorForeground: "#0a0e0a",
    focusRing: "#c770ff",
    foreground: "#62ff94",
    info: "#30b3ff",
    infoForeground: "#0a0e0a",
    muted: "#050805",
    mutedForeground: "#8ca391",
    primary: "#2eff6a",
    primaryForeground: "#0a0e0a",
    secondary: "#0f140f",
    secondaryForeground: "#62ff94",
    selection: "#2eff6a",
    selectionForeground: "#0a0e0a",
    success: "#62ff94",
    successForeground: "#0a0e0a",
    warning: "#e6ff57",
    warningForeground: "#0a0e0a",
  },
  name: "matrix",
  spacing: {
    0: 0,
    1: 1,
    2: 2,
    3: 3,
    4: 4,
    6: 6,
    8: 8,
  },
  typography: {
    base: "",
    bold: true,
    lg: "bold",
    sm: "dim",
    xl: "bold",
  },
};
